import Link from 'next/link'
import { ArrowLeft, Heart, ShieldCheck, Sparkles, LifeBuoy } from 'lucide-react'
import { Button } from '@/components/ui/button'

const pages = {
  about: { label: 'About MindSpace', title: 'A calmer way to understand your everyday wellbeing.', description: 'MindSpace brings reflection, habits, check-ins, and personal trends into one private space built for real routines.', icon: Sparkles, items: [['Small progress, made visible', 'Track the daily actions that support you and notice patterns without judgment.'], ['Designed for real routines', 'Quick check-ins and flexible habit goals fit between classes, work, and everything else.']] },
  features: { label: 'Features', title: 'Everything you need for a more intentional day.', description: 'Build a personal picture of your wellbeing with tools that work together instead of competing for your attention.', icon: Sparkles, items: [['Track your signals', 'Log moods, habits, reflections, sleep, water, and goals in one dashboard.'], ['Grow consistent habits', 'Use the visual habit grid, streaks, reminders, monthly goals, and progress graph.'], ['See your patterns', 'Personal insights turn your check-ins into clear trends that help you decide what to try next.']] },
  support: { label: 'Support', title: 'You do not have to figure it out alone.', description: 'If MindSpace is not behaving as expected, start with these gentle reminders.', icon: LifeBuoy, items: [['Data is missing', 'Sign out and back in, then check your connection. Your data is loaded from your account-specific records.'], ['Need urgent help?', 'MindSpace is not an emergency service. Contact your local emergency number or campus counseling service for immediate support.']] },
  privacy: { label: 'Privacy', title: 'Your wellness data belongs to you.', description: 'MindSpace keeps your account data separated by your authenticated user ID and gives you tools to export or clear it.', icon: ShieldCheck, items: [['Account-scoped data', 'Entries, habits, and insights are requested only for the signed-in account.'], ['Your controls', 'Use Settings to download a JSON copy or clear your stored wellness records.'], ['A gentle reminder', 'Do not use MindSpace as a replacement for professional medical advice or emergency care.']] },
} as const

export function InfoPage({ page }: { page: keyof typeof pages }) {
  const content = pages[page]; const Icon = content.icon
  return <main className="min-h-screen bg-background px-5 py-8"><nav className="mx-auto flex max-w-5xl items-center justify-between"><Link href="/" className="flex items-center gap-2 font-serif text-xl"><Heart className="text-primary" size={19} />MindSpace</Link><Link href="/"><Button variant="ghost">Back home</Button></Link></nav><section className="mx-auto max-w-4xl py-20"><Link href="/" className="mb-10 inline-flex items-center gap-2 text-sm text-primary hover:underline"><ArrowLeft size={15} />Back to home</Link><div className="max-w-2xl"><div className="mb-4 inline-flex items-center gap-2 rounded-full bg-primary/10 px-3 py-1 text-sm text-primary"><Icon size={15} />{content.label}</div><h1 className="text-balance text-4xl font-semibold sm:text-6xl">{content.title}</h1><p className="mt-5 text-lg leading-8 text-muted-foreground">{content.description}</p></div><div className="mt-12 grid gap-5 md:grid-cols-2">{content.items.map(([title, text]) => <article key={title} className="rounded-3xl border border-white/10 bg-white/[0.045] p-6"><h2 className="text-xl font-semibold">{title}</h2><p className="mt-3 leading-7 text-muted-foreground">{text}</p></article>)}</div></section></main>
}
